#### Problem Statement

Any companines 2014-2018 sales data to identify key revenue and profit drivers across products, channels, and regions , uncover sesonla trends and outliers, and align perfomance against budgets. use these insights to optimize pricing, promotions and market expansion for sustainable growth and reduced concentartion risk.

In [33]:
# importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [34]:
# read a data and stored it in sheets variable and below separted each data in separate table
sheets = pd.read_excel('Regional Sales Dataset.xlsx', sheet_name= None)
print(sheets)

{'Sales Orders':         OrderNumber  OrderDate  Customer Name Index      Channel  \
0       SO - 000225 2014-01-01                  126    Wholesale
1      SO - 0003378 2014-01-01                   96  Distributor
2      SO - 0005126 2014-01-01                    8    Wholesale
3      SO - 0005614 2014-01-01                   42       Export
4      SO - 0005781 2014-01-01                   73    Wholesale
...             ...        ...                  ...          ...
64099  SO - 0007573 2018-02-28                   74    Wholesale
64100  SO - 0007706 2018-02-28                   51       Export
64101  SO - 0007718 2018-02-28                  136  Distributor
64102  SO - 0008084 2018-02-28                  158  Distributor
64103  SO - 0008654 2018-02-28                   22  Distributor

      Currency Code Warehouse Code  Delivery Region Index  \
0               USD         AXW291                    364
1               USD         AXW291                    488
2               USD         AXW291                    155
3               USD         AXW291                    473
4               USD         AXW291                    256
...             ...            ...                    ...
64099           USD         AXW291                    825
64100           USD         NXH382                    444
64101           USD         AXW291                    312
64102           USD         AXW291                    737
64103           USD         AXW291                    807

       Product Description Index  Order Quantity  Unit Price  Line Total  \
0                             27               6      2499.1     14994.6
1                             20              11      2351.7     25868.7
2                             26               6       978.2      5869.2
3                              7               7      2338.3     16368.1
4                              8               8      2291.4     18331.2
...                          ...             ...         ...         ...
64099                         26              12      1815.7     21788.4
64100                         21               6       864.3      5185.8
64101                         13              11      3953.0     43483.0
64102                         20               7      3959.7     27717.9
64103                         15               8       998.3      7986.4

       Total Unit Cost
0             1824.343
1             1269.918
2              684.740
3             1028.852
4             1260.270
...                ...
64099          980.478
64100          579.081
64101         2648.510
64102         2930.178
64103          848.555

[64104 rows x 12 columns], 'Customers':      Customer Index Customer Names
0                 1  Geiss Company
1                 2  Jaxbean Group
2                 3     Ascend Ltd
3                 4      Eire Corp
4                 5   Blogtags Ltd
..              ...            ...
170             171   Accord Group
171             172   BB17 Company
172             173          H Ltd
173             174   Tekfly Group
174             175   SHISEIDO Ltd

[175 rows x 2 columns], 'Regions':       id        name                                   county state_code  \
0      1      Auburn                               Lee County         AL
1      2  Birmingham           Shelby County/Jefferson County         AL
2      3     Decatur           Limestone County/Morgan County         AL
3      4      Dothan  Dale County/Houston County/Henry County         AL
4      5      Hoover           Shelby County/Jefferson County         AL
..   ...         ...                                      ...        ...
989  990      Racine                            Racine County         WI
990  991    Waukesha                          Waukesha County         WI
991  992  West Allis                         Milwaukee County         WI
992  993      Casper                           Natrona County         WY
993  994    Cheyenne                           Laramie County         WY

         state  type  latitude  longitude  area_code  population  households  \
0      Alabama  City  32.60986  -85.48078        334       62059       21767
1      Alabama  City  33.52744  -86.79905        205      212461       89972
2      Alabama  City  34.57332  -86.99214        256       55437       22294
3      Alabama  City  31.23370  -85.40682        334       68567       25913
4      Alabama  City  33.37695  -86.80558        205       84848       32789
..         ...   ...       ...        ...        ...         ...         ...
989  Wisconsin  City  42.72613  -87.78285        262       77742       29851
990  Wisconsin  City  43.01168  -88.23148        262       71970       28331
991  Wisconsin  City  43.01668  -88.00703        414       60620       27457
992    Wyoming  City  42.86663 -106.31308        307       60285       23814
993    Wyoming  City  41.13998 -104.82025        307       63335       25130

     median_income  land_area  water_area        time_zone
0            38342  152375113     2646161  America/Chicago
1            31061  378353942     6591013  America/Chicago
2            41496  141006257    17594716  America/Chicago
3            42426  232166237      835468  America/Chicago
4            77146  122016784     2553332  America/Chicago
..             ...        ...         ...              ...
989          41455   40111757     8282116  America/Chicago
990          59547   65856921      700602  America/Chicago
991          45221   29480532       60789  America/Chicago
992          57790   68507280      911081   America/Denver
993          58219   69964749      282335   America/Denver

[994 rows x 15 columns], 'State Regions':        Column1               Column2    Column3
0   State Code                 State     Region
1           AL               Alabama      South
2           AR              Arkansas      South
3           AZ               Arizona       West
4           CA            California       West
5           CO              Colorado       West
6           CT           Connecticut  Northeast
7           DC  District of Columbia      South
8           DE              Delaware      South
9           FL               Florida      South
10          GA               Georgia      South
11          HI                Hawaii       West
12          IA                  Iowa    Midwest
13          ID                 Idaho       West
14          IL              Illinois    Midwest
15          IN               Indiana    Midwest
16          KS                Kansas    Midwest
17          KY              Kentucky      South
18          LA             Louisiana      South
19          MA         Massachusetts  Northeast
20          MD              Maryland      South
21          ME                 Maine  Northeast
22          MI              Michigan    Midwest
23          MN             Minnesota    Midwest
24          MO              Missouri    Midwest
25          MS           Mississippi      South
26          MT               Montana       West
27          NC        North Carolina      South
28          ND          North Dakota    Midwest
29          NE              Nebraska    Midwest
30          NH         New Hampshire  Northeast
31          NJ            New Jersey  Northeast
32          NM            New Mexico       West
33          NV                Nevada       West
34          NY              New York  Northeast
35          OH                  Ohio    Midwest
36          OK              Oklahoma      South
37          OR                Oregon       West
38          PA          Pennsylvania  Northeast
39          RI          Rhode Island  Northeast
40          SC        South Carolina      South
41          SD          South Dakota    Midwest
42          TN             Tennessee      South
43          TX                 Texas      South
44          UT                  Utah       West
45          VA              Virginia      South
46          WA            Washington       West
47          WI             Wisconsin    Midwest
48          WY               Wyoming       West, 'Products':     Index Product Name
0       1    Product 1
1       2    Product 2
2       3    Product 3
3       4    Product 4
4       5    Product 5
5       6    Product 6
6       7    Product 7
7       8    Product 8
8       9    Product 9
9      10   Product 10
10     11   Product 11
11     12   Product 12
12     13   Product 13
13     14   Product 14
14     15   Product 15
15     16   Product 16
16     17   Product 17
17     18   Product 18
18     19   Product 19
19     20   Product 20
20     21   Product 21
21     22   Product 22
22     23   Product 23
23     24   Product 24
24     25   Product 25
25     26   Product 26
26     27   Product 27
27     28   Product 28
28     29   Product 29
29     30   Product 30, '2017 Budgets':    Product Name  2017 Budgets
0     Product 1   3016489.209
1     Product 2   3050087.565
2     Product 3   2642352.432
3     Product 4   2885560.824
4     Product 5   3925424.542
5     Product 6   1672229.416
6     Product 7    889737.555
7     Product 8   1085037.329
8     Product 9    710415.405
9    Product 10    864331.624
10   Product 11   1230458.484
11   Product 12   1356976.996
12   Product 13   3720639.645
13   Product 14   4028698.409
14   Product 15   3299478.315
15   Product 16   2062061.144
16   Product 17   2119616.824
17   Product 18   2309499.045
18   Product 19   1645841.600
19   Product 20   2067108.120
20   Product 21    959899.218
21   Product 22    663601.902
22   Product 23   1135815.758
23   Product 24    756557.970
24   Product 25   5342315.484
25   Product 26   5685138.270
26   Product 27    964940.231
27   Product 28   1003867.767
28   Product 29    594471.570
29   Product 30   1011609.684}

In [35]:
# Assign dataframes to each sheet, we used sheets above it means
# a dataframe in which data is stored in row and coloumn table format
# now we will seprate a each table from sheets where we have dataframe 
#i.e all tables are created here will seprate each

df_sales = sheets['Sales Orders']
df_customers = sheets['Customers']
df_products = sheets['Products']
df_regions = sheets['Regions']
df_state_reg = sheets['State Regions']
df_budgets = sheets['2017 Budgets']

In [37]:
# analyzing a shape of each table
print("df_sales shape:", (df_sales.shape))
print("df_customers shape:", (df_customers.shape))
print("df_products shape:", (df_products.shape))
print("df_regions:", (df_regions.shape))
print("df_state_reg shape:", (df_state_reg.shape))
print("df_budgets shape:", (df_budgets.shape))

df_sales shape: (64104, 12)
df_customers shape: (175, 2)
df_products shape: (30, 2)
df_regions: (994, 15)
df_state_reg shape: (49, 3)
df_budgets shape: (30, 2)

In [38]:
df_sales.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

In [39]:
df_customers.head(5)

   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

In [40]:
df_products.head(5)

   Index Product Name
0      1    Product 1
1      2    Product 2
2      3    Product 3
3      4    Product 4
4      5    Product 5

In [41]:
df_regions.head(5)

,id,name,county,state_code,state,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,1,Auburn,Lee County,AL,Alabama,City,32.60986,-85.48078,334,62059,21767,38342,152375113,2646161,America/Chicago
1,2,Birmingham,Shelby County/Jefferson County,AL,Alabama,City,33.52744,-86.79905,205,212461,89972,31061,378353942,6591013,America/Chicago
2,3,Decatur,Limestone County/Morgan County,AL,Alabama,City,34.57332,-86.99214,256,55437,22294,41496,141006257,17594716,America/Chicago
3,4,Dothan,Dale County/Houston County/Henry County,AL,Alabama,City,31.23370,-85.40682,334,68567,25913,42426,232166237,835468,America/Chicago
4,5,Hoover,Shelby County/Jefferson County,AL,Alabama,City,33.37695,-86.80558,205,84848,32789,77146,122016784,2553332,America/Chicago

In [42]:
df_state_reg.head(5)

      Column1     Column2 Column3
0  State Code       State  Region
1          AL     Alabama   South
2          AR    Arkansas   South
3          AZ     Arizona    West
4          CA  California    West

In [43]:
df_budgets.head(5)

  Product Name  2017 Budgets
0    Product 1   3016489.209
1    Product 2   3050087.565
2    Product 3   2642352.432
3    Product 4   2885560.824
4    Product 5   3925424.542

In [44]:
# now see in state_reg table colunm name is in 0th row state code and 
# all so we need to treat that row as column so we have done this

new_header = df_state_reg.iloc[0]
df_state_reg.columns = new_header
df_state_reg = df_state_reg[1:].reset_index(drop=True)

df_state_reg.head(5)

0 State Code       State Region
0         AL     Alabama  South
1         AR    Arkansas  South
2         AZ     Arizona   West
3         CA  California   West
4         CO    Colorado   West

In [45]:
#To check whether a nulls values are present
df_sales.isnull().sum()

OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

In [46]:
df_regions.isnull().sum()

id               0
name             0
county           0
state_code       0
state            0
type             0
latitude         0
longitude        0
area_code        0
population       0
households       0
median_income    0
land_area        0
water_area       0
time_zone        0
dtype: int64

In [47]:
df_budgets.isnull().sum()

Product Name    0
2017 Budgets    0
dtype: int64

In [48]:
df_customers.isnull().sum()

Customer Index    0
Customer Names    0
dtype: int64

In [49]:
df_products.isnull().sum()

Index           0
Product Name    0
dtype: int64

In [50]:
df_state_reg.isnull().sum()

0
State Code    0
State         0
Region        0
dtype: int64

# Data Cleaning and Wrangling

In [51]:
#merging customers table in sales table in new table df
df = df_sales.merge(
    df_customers,
    how='left',
    left_on='Customer Name Index',
    right_on='Customer Index'
)

In [52]:
df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group

In [53]:
#Merge with products table
df= df.merge(
    df_products,
    how='left',
    left_on='Product Description Index',
    right_on='Index'
)

In [54]:
df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names,Index,Product Name
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd,27,Product 27
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd,20,Product 20
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp,26,Product 26
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group,7,Product 7
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group,8,Product 8

In [55]:
#Merge with Regions

df= df.merge(
    df_regions,
    how='left',
    left_on='Delivery Region Index',
    right_on='id'
)

In [56]:
df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,City,32.08354,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,City,39.61366,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,City,37.66243,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,City,39.16533,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,Town,41.77524,-72.52443,959,58007,24141,63158,70972793,720300,America/New York

In [57]:
# Merge with State Region

df= df.merge(
    df_state_reg[["State Code", "Region"]],
    how='left',
    left_on='state_code',
    right_on='State Code'
)

In [58]:
df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,State Code,Region
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,GA,South
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,IN,Midwest
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,CA,West
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,IN,Midwest
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,CT,Northeast

In [59]:
# Merge with budgets

df = df.merge(
    df_budgets,
    how='left',
    on='Product Name'
)

In [61]:
# to save this new data frame 
df.to_csv('file.csv')

In [62]:
# redundant columns in df table
#Customer Index
#Index
#id
#State Code

# clean up redundant columns 
cols_to_drop = ['Customer Index', 'Index', 'id', 'State Code']
df = df.drop(columns= cols_to_drop,errors='ignore')

df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,Region,2017 Budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,Northeast,1085037.329

In [63]:
# Convert all columns to lower case for consitency and easier access
df.columns = df.columns.str.lower()

df.columns.values

array(['ordernumber', 'orderdate', 'customer name index', 'channel',
       'currency code', 'warehouse code', 'delivery region index',
       'product description index', 'order quantity', 'unit price',
       'line total', 'total unit cost', 'customer names', 'product name',
       'name', 'county', 'state_code', 'state', 'type', 'latitude',
       'longitude', 'area_code', 'population', 'households',
       'median_income', 'land_area', 'water_area', 'time_zone', 'region',
       '2017 budgets'], dtype=object)

In [66]:
# KEEP THE IMPORTANT COLUMNS AND DELETE THE COLUMNS THAT WE DON'T NEED

cols_to_keep = [
    'ordernumber',
    'orderdate',
    'customer names',
    'channel',
    'product name',
    'order quantity',
    'unit price',
    'line total',
    'total unit cost',
    'state_code',
    'county',
    'state',
    'region',
    'latitude',
    'longitude',
    '2017 budgets'
   
]

In [67]:
# again table which we only want 
df = df[cols_to_keep]

In [69]:
df.head(5)

,ordernumber,orderdate,customer names,channel,product name,order quantity,unit price,line total,total unit cost,state_code,county,state,region,latitude,longitude,2017 budgets
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,964940.231
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,2067108.120
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,5685138.270
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,889737.555
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,1085037.329